'use client';

import { useMemo, useState } from 'react';
import type { AuditLog, CrmUserProfile } from '@/types/database';

const actionLabels: Record<string, string> = { lead_assigned: 'Responsável alterado', user_invited: 'Usuário convidado', user_updated: 'Usuário atualizado', campaign_created: 'Campanha criada', campaign_updated: 'Campanha atualizada', template_created: 'Template criado', template_version_created: 'Nova versão de template', template_state_updated: 'Estado do template alterado', conversion_queued: 'Conversão preparada', conversion_requeued: 'Conversão recolocada na fila' };
export function AuditViewer({ logs, profiles }: { logs: AuditLog[]; profiles: CrmUserProfile[] }) {
  const [filters, setFilters] = useState({ search: '', actor: '', entity: '', action: '', start: '', end: '' });
  const profileMap = useMemo(() => new Map(profiles.map((profile) => [profile.user_id, profile.display_name ?? 'Usuário'])), [profiles]);
  const filtered = useMemo(() => logs.filter((log) => (!filters.search || JSON.stringify(log).toLowerCase().includes(filters.search.toLowerCase())) && (!filters.actor || log.actor_user_id === filters.actor) && (!filters.entity || log.entity_type === filters.entity) && (!filters.action || log.action === filters.action) && (!filters.start || log.created_at >= `${filters.start}T00:00:00`) && (!filters.end || log.created_at <= `${filters.end}T23:59:59`)), [logs, filters]);
  return <div className="space-y-4"><div className="panel grid gap-3 md:grid-cols-2 xl:grid-cols-6"><label className="field xl:col-span-2">Busca<input className="control" value={filters.search} onChange={(e) => setFilters({ ...filters, search: e.target.value })} placeholder="Entidade, ação ou conteúdo" /></label><label className="field">Usuário<select className="control" value={filters.actor} onChange={(e) => setFilters({ ...filters, actor: e.target.value })}><option value="">Todos</option>{profiles.map((p) => <option key={p.user_id} value={p.user_id}>{p.display_name}</option>)}</select></label><label className="field">Entidade<select className="control" value={filters.entity} onChange={(e) => setFilters({ ...filters, entity: e.target.value })}><option value="">Todas</option>{[...new Set(logs.map((log) => log.entity_type))].map((value) => <option key={value}>{value}</option>)}</select></label><label className="field">De<input className="control" type="date" value={filters.start} onChange={(e) => setFilters({ ...filters, start: e.target.value })} /></label><label className="field">Até<input className="control" type="date" value={filters.end} onChange={(e) => setFilters({ ...filters, end: e.target.value })} /></label></div><div className="space-y-3">{filtered.map((log) => <article className="panel" key={log.id}><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-semibold">{actionLabels[log.action] ?? log.action}</p><p className="text-xs text-slate-500">{log.entity_type} {log.entity_id ? `· ${log.entity_id}` : ''}</p></div><div className="text-right text-xs text-slate-500"><p>{log.actor_user_id ? profileMap.get(log.actor_user_id) ?? 'Usuário removido' : log.actor_type}</p><time>{new Date(log.created_at).toLocaleString('pt-BR')}</time></div></div><details className="mt-3 text-xs text-slate-400"><summary className="cursor-pointer text-amber-300">Ver alterações</summary><div className="mt-2 grid gap-2 md:grid-cols-2"><pre className="overflow-auto rounded-lg bg-slate-950 p-3">Antes: {JSON.stringify(log.before_data, null, 2)}</pre><pre className="overflow-auto rounded-lg bg-slate-950 p-3">Depois: {JSON.stringify(log.after_data, null, 2)}</pre></div></details></article>)}</div>{filtered.length === 0 && <div className="panel text-center text-slate-500">Nenhum registro corresponde aos filtros.</div>}</div>;
}
