'use client';

import { useState } from 'react';
import type { MessageTemplate } from '@/types/database';

export function TemplatesManager({ initialTemplates }: { initialTemplates: MessageTemplate[] }) {
  const [templates, setTemplates] = useState(initialTemplates);
  const [feedback, setFeedback] = useState<string | null>(null);
  const [form, setForm] = useState({ name: '', body: '', approved: false, base_id: '' });
  const [previewName, setPreviewName] = useState('Maria');
  async function save(event: React.FormEvent) { event.preventDefault(); const response = await fetch('/api/admin/templates', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const payload = await response.json(); if (!response.ok) return setFeedback(payload.error); setTemplates((current) => [payload.template, ...current]); setForm({ name: '', body: '', approved: false, base_id: '' }); setFeedback('Nova versão salva sem alterar o histórico anterior.'); }
  async function toggle(template: MessageTemplate, change: Partial<MessageTemplate>) { const response = await fetch('/api/admin/templates', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: template.id, ...change }) }); const payload = await response.json(); if (!response.ok) return setFeedback(payload.error); setTemplates((current) => current.map((item) => item.id === template.id ? { ...item, ...change } : item)); }
  function versionFrom(template: MessageTemplate) { setForm({ name: template.name, body: template.body, approved: false, base_id: template.id }); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  return <div className="space-y-6">
    <form className="panel grid gap-4 lg:grid-cols-2" onSubmit={save}><div className="space-y-3"><label className="field">Nome<input className="control" required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label className="field">Mensagem<textarea className="control min-h-36 resize-y normal-case" required value={form.body} onChange={(e) => setForm({ ...form, body: e.target.value })} placeholder="Olá, {{nome}}!" /></label><label className="flex items-center gap-2 text-sm text-slate-300"><input type="checkbox" checked={form.approved} onChange={(e) => setForm({ ...form, approved: e.target.checked })} /> Aprovar esta versão ao salvar</label><button className="button-primary">{form.base_id ? 'Criar nova versão' : 'Criar template'}</button></div><div className="rounded-xl border border-slate-800 bg-slate-950 p-4"><label className="field">Nome usado no preview<input className="control" value={previewName} onChange={(e) => setPreviewName(e.target.value)} /></label><p className="panel-title mt-5">Pré-visualização</p><div className="mt-2 max-w-md rounded-2xl rounded-bl-sm bg-emerald-900/50 p-4 text-sm leading-6 text-slate-100">{(form.body || 'Sua mensagem aparecerá aqui.').replaceAll('{{nome}}', previewName || 'Cliente')}</div><p className="mt-3 text-xs text-slate-500">Variáveis suportadas nesta etapa: {'{{nome}}'}.</p></div></form>
    {feedback && <p role="status" className="text-sm text-amber-300">{feedback}</p>}
    <section className="grid gap-4 xl:grid-cols-2">{templates.map((template) => <article className="panel" key={template.id}><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold">{template.name} <span className="text-xs text-slate-500">v{template.version}</span></h2><p className="mt-1 text-xs text-slate-500">{template.approved ? 'Aprovado' : 'Aguardando aprovação'} · {template.active ? 'Ativo' : 'Inativo'}</p></div><span className={template.approved ? 'rounded-full bg-emerald-500/10 px-2 py-1 text-xs text-emerald-300' : 'rounded-full bg-amber-500/10 px-2 py-1 text-xs text-amber-300'}>{template.approved ? 'Aprovado' : 'Rascunho'}</span></div><p className="mt-4 whitespace-pre-wrap rounded-xl bg-slate-950 p-4 text-sm text-slate-300">{template.body}</p><div className="mt-4 flex flex-wrap gap-2"><button className="button-secondary" onClick={() => versionFrom(template)}>Nova versão</button><button className="button-secondary" onClick={() => void toggle(template, { approved: !template.approved })}>{template.approved ? 'Reprovar' : 'Aprovar'}</button><button className="button-secondary" onClick={() => void toggle(template, { active: !template.active })}>{template.active ? 'Desativar' : 'Ativar'}</button></div></article>)}</section>
  </div>;
}
